# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Stir Trek
subtitle: Stir Trek Conference
description: Stir Trek is a one-day conference in Columbus, Ohio focused on teaching software developers the latest and greatest in technologies, techniques, and tools. The full day of content is always concluded with a private screening of a blockbuster film on its opening day.
keywords: Technical Conference, StirTrek, Stir Trek, web, mobile, cloud, conference, software, developer, designer, community
author: Stir Trek Conference
language: EN-US
utcOffset: "-0400"

# To support multiple years of archives, update the currentYear and add the old one to the allYears array
currentYear: 2023
allYears:
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
showSchedule: true
showSessionList: false
showSpeakers: true
# If you'd like to show the speaker survey link in the schedule, you need to turn this on and configure it
# Add a custom speaker question and put hte name in "surveyQuestionName"
showSurveyOnSchedule: false
surveyUrl: https://docs.google.com/forms/d/e/1FAIpQLSdB_bb2bX1qDfCDvIX_Fgm431l1a-CFqqRZyO-Ja6F0RX6Rxg/viewform?usp=pp_url&entry.847701887=
surveyQuestionName: SurveyFeedbackToken

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://stirtrek.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Social Media
twitterHandle: "@StirTrek"
socialMediaImage: /icons/opengraph.jpg

# Sessionize API
## This needs updated each year as we have a separate Sessionize Instance. Directions for setting up the API are in the readme
## Use the All Data API
sessionizeApiUrl: "https://sessionize.com/api/v2/chte13vg/view/All"

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
#external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
# per_page: 10
# pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stir-trek-comic

# Deployment
## Docs: https://hexo.io/docs/deployment.html
## repo: https://__GITHUB_TOKEN__@github.com/stirtrek/stirtrek.github.io
## repo: https://github.com/stirtrek/stirtrek.github.io.git
deploy:
  type: git
  repo:
    github:
      url: https://github.com/stirtrek/stirtrek.github.io.git/
      branch: master
