name: Nightly Content Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allow manual triggering of the workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: source  # Ensures we check out the source branch
          persist-credentials: false  # Required for committing later
          fetch-depth: 0  # Needed for pushing changes

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Configure Git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'GitHub Actions Bot'
          email: 'github-actions[bot]@users.noreply.github.com'
          actor: ${{ github.actor }}
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Install dependencies
        run: npm install

      - name: Run download script
        run: node ./scripts-manuallyexecuting/download-sessionize-details.js

      - name: Run build schedule script
        run: node ./scripts-manuallyexecuting/build-schedule-from-sessions.js

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Nightly content update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"
          git push origin source
